f/simplewoundingsystem/fn_LifeTick.sqf
* Fixes SWS bleedout timer
Bleedout timer has been broken for some time, this finally fixes it.
* Fixes formatting on SWS bleedout timer fix
=> Fixes SWS bleedout timer (#789)

stringtable.xml
Errors were not causing noticable problems ingame, but cause issues with external editors
=> Fixes minor stringtable.xml errors

f/EandEcheck/f_EandECheckLoop.sqf, f/FTMemberMarkers/fn_LocalFTMarkerSync.sqf, f/JIP/f_JIP_nearTargetGroupCheck.sqf, f/assignGear/f_assignGear_AI.sqf, f/briefing/f_briefing_admin.sqf, f/casualtiesCap/f_CasualtiesCapCheck.sqf, f/groupJoin/f_groupJoinAction.sqf, f/mapClickTeleport/fn_mapClickTeleportUnit.sqf, f/mpEnd/fn_mpEnd.sqf, f/safeStart/f_safeStartLoop.sqf, f/setAISkill/f_setAISkill.sqf, f/simplewoundingsystem/fn_OnDamage.sqf, f/simplewoundingsystem/fn_OnDeath.sqf, f/simplewoundingsystem/fn_OnHeal.sqf, f/simplewoundingsystem/fn_SetDowned.sqf, f/simplewoundingsystem/init.sqf, f/spect/fn_EventHandler.sqf, f/zeus/fn_zeusInit.sqf, ws_fnc/misc/fn_broadcast.sqf
=> Replaced all calls to BIS_fnc_MP with remoteExec and remoteExecCall

f/missionConditions/fn_SetWeather.sqf
Fixes #17 
Changes SetWeather to have a 4th parameter for transition. Fixes type errors while supporting old syntax
=> Fixes #17 

f/briefing/f_orbatNotes.sqf
Briefing ORBAT now lists JTAC and FAC, similar to medic
=> Added JTAC and FAC to ORBAT list

f/authorisedCrew/fn_authorisedCrewCheck.sqf
Recreated to fix the incorrect inclusion of changes in f95a75f
=> Authorised Crew Check: Fixed array update bug (Mk2)

briefing.sqf, f/briefing/f_briefing_civ.sqf
Added briefing support for the IDAP faction. These units will be shown the civilian briefing. ref issue #35
=> Issue 35 - IDAP briefing

description.ext
=> Removed redundant loading screen related variables from description.ext

f/assignGear/f_assignGear_clothes.sqf, f/assignGear/f_assignGear_fia_light.sqf, f/assignGear/f_assignGear_fia_standard.sqf, f/assignGear/f_assignGear_fia_v.sqf
=> Issue-41 Replace BIS_fnc_selectRandom with selectRandom

f/disableThermals/fn_disableThermals.sqf
Added support for assembled vehicles (e.g. UAVs) to Disable Thermals component.
=> Disable Thermals: Support for assembled vehicles

f/assignGear/f_assignGear_aaf_v.sqf
AAF car and truck inventories now carries same number of items as other factions
Ref: #40
=> issue-40: AAF car and truck inventories

f/nametag/include/f_nametagBrief.sqf, f/nametag/include/f_nametagDisableKey.sqf
=> #63: Fixed issue with nametags if "Time acceleration" key is unbound

f/assignGear/f_assignGear_aaf.sqf
=> Fix incorrect smoke color

f/mpEnd/fn_mpEnd.sqf
see ferstaberinde/F3#776 and #75
=> mpEnd: avoid triggering of multiple endings

f/zeus/fn_zeusInit.sqf
=> [#82] Fixed script error due to invalid enum string

f/medical/init.sqf
=> medical: Remove "Wait to be revived" holdAction

f/functions.hpp, f/mpEnd/fn_mpEndReceiver.sqf, f/spect/fn_terminateSpectator.sqf
Potentially resolves isue #108.
I tested it and it doesn't break anything, 
but since I couldn't reproduce it, 
I'm unsure if it definitely resolves the spectator ending issue,
=> EG spectator ending bug hotfix

f/nametag/functions/fn_nametagCache.sqf, f/nametag/functions/fn_nametagDraw.sqf, f/nametag/functions/fn_nametagGetData.sqf, f/nametag/functions/fn_nametagResetFont.sqf, f/nametag/functions/fn_nametagUpdate.sqf, f/nametag/include/f_nametagBrief.sqf, f/nametag/include/f_nametagCacheLoop.sqf, f/nametag/include/f_nametagDisableKey.sqf, f/nametag/include/f_nametagInitTalking.sqf
Fixes an issue where `_namecolor` and `_team` (in the file `f\nametag\functions\fn_nametagGetData.sqf`) were not defined and lead to a error shown ingame.
=> nametag: Hotfix for uninitialized variables

description.ext, f/cache/fn_cInit.sqf, f/cache/fn_cTracker.sqf, f/cache/fn_gCache.sqf, f/cache/fn_gUncache.sqf, f/functions.hpp, init.sqf
This pull request solves issue #115.
Note: This PR might still change depending on the outcome of the discussion in #115.
=> Issue 115: Restore cache component

f/disableThermals/fn_disableThermals.sqf, init.sqf
This pull request fixes issue #126.
Additionally now the component supports running it more than once, which is useful for dynamically spawned vehicles.
=> Issue 126: run disableThermals only on server and allow running more than once.

f/briefing/f_orbatNotes.sqf
See #131 for more information this bug.
=> Orbat briefing should wait for setGroupIDs

mission.sqm
This PR resolves issue #119.
It's split up into 2 different commits:
The first one upgrades the sqm file to the latest version,
and the second one contains the actual changes.
=> Issue 119: Add spectator slots

mission.sqm
**Warning: do not merge this PR unless PR #133 is already merged.
Once #133 is merged, there should only be one single commit in this pull request.
In case #133 is not going to be merged, I will update this pull request accordingly.**
Workaround for https://feedback.bistudio.com/T127759
=> Spectator init field

f/dynamicViewDistance/f_setViewDistanceInit.sqf
Hotfiox for #96. 
Related to #37.
see https://feedback.bistudio.com/T127838
=> Add GetInMan event handler to dynamicViewDistance

description.ext
=> Issue 170: Use missiondefault for weather/time.

description.ext, f/groupJoin/f_groupJoinAction.sqf, stringtable.xml
=> Issue 169: Remove JIP from cfgNotifications

description.ext, f/spect/fn_activateSpectator.sqf
=> Issue 114: Fixed disappearing tags. Using BIS method to remove death blur

mission.sqm
This PR resolves issue #181 (and #122).
Changes:
* Updated Marid vehicle class and removed its commander slot.
* Updated helicopters to use the dynamic loadout variant. (Follow-up from #124 / #122)
=> issue 181: Update vehicle classes

ws_fnc/AI/fn_createGarrison.sqf
Fixes:
- Fix a bug with toLower where it would fail when a list of classes was provided.
New features: 
- Add support for providing list of buildings 
(to bypass the building finding thing inside createGarrison. this is useful when a seperate script controls which buildings should be garrisoned).
- Add support for min-radius 
(this can be useful for placing different amount of units near some objectives, and yet another different number farther away, etc).
There are no new parameters and it's still completely compatible with older versions.
But if the new features are entirely unwanted, I can remove them from this PR.
=> Fix and improve createGarrison

README.md, description.ext, mission.sqm
To be merged once all open pull requests for 3.5.2 have been merged and tested.
(I hope git can auto-merge this after #191)
=> bump version to 3.5.2

mission.sqm
This pull request closes issue #202.
=> Issue 202: Fix slotting order for Gendarme

f/setTeamColours/f_setTeamColours.sqf
This pull request closes issue #201.
=> Issue 201: setTeamColours doesn't work when the group leader is an AI

mission.sqm
=> issue 217: rename VehSyn_TH1_1 to VehSyn_TH1

mission.sqm
=> Issue 225: Fix inconsistent slotting descriptions

mission.sqm
=> Issue 216: Change unit type of CAS1 from helipilot_F to Fighter_Pilot_F

f/assignGear/f_assignGear_3IFB_v.sqf, f/assignGear/f_assignGear_aaf_v.sqf, f/assignGear/f_assignGear_csat_v.sqf, f/assignGear/f_assignGear_ctrg_v.sqf, f/assignGear/f_assignGear_fia_v.sqf, f/assignGear/f_assignGear_nato_v.sqf, f/assignGear/f_assignGear_syndikat_v.sqf
=> [#203][assignGear] Add bags to IFVs, tanks, and trucks

mission.sqm
=> Issue 184 template enable unit data link

f/assignGear/f_assignGear_csatPacific.sqf, f/assignGear/f_assignGear_natoPacific.sqf, f/assignGear/f_assignGear_syndikat.sqf
=> issue 233: Use new magazine classes

f/assignGear/f_assignGear_AI.sqf, f/assignGear/f_assignInsignia.sqf, f/assignGear/fn_assignGear.sqf, f/briefing/fn_createBriefing.sqf, f/casualtiesCap/f_CasualtiesCapCheck.sqf, f/common/fn_setVirtualFaction.sqf, f/common/fn_virtualFaction.sqf, f/functions.hpp, f/groupMarkers/f_setLocalGroupMarkers.sqf
=> Issue 234 add virtual faction support

f/assignGear/f_assignInsignia.sqf, f/assignGear/fn_assignGear.sqf, f/briefing/f_briefing_3ifb.sqf, f/briefing/fn_createBriefing.sqf, f/groupMarkers/f_setLocalGroupMarkers.sqf, f/groupMarkers/fn_groupData.sqf, mission.sqm
=> Issue 212 add 3IFB

f/assignGear/f_assignGear_3IFB.sqf, f/assignGear/f_assignGear_ctrg.sqf, f/assignGear/f_assignGear_syndikat.sqf
=> Issue 210: add hsamag bags for 3ifb,ctrg,syndikat

f/assignGear/f_assignGear_npr.sqf, f/assignGear/f_assignGear_spetsnaz.sqf, f/assignGear/f_assignInsignia.sqf
This PR contains fixes, discovered in dev/testing, for Contact-related changes to assignGear and similar components.
=> Contact gear fixes

f/assignGear/fn_assignGear.sqf, f/assignGear/fn_assignInsignia.sqf, f/functions.hpp
~~Important fixes:~~
* ~~Fix `_NATO_Medic_Badge"` (this made assignGear fail silently) (Also fixed in #260)~~
* ~~Fix lowercase factions (Also fixed in #260)~~
Non-essential changes:
* Seperate function instead of include (this way it won't kill assignGear if it fails (to compile))
* Fix warnings about private variables
* `params` for `_insignia_styles` because why not
=> assignInsignia fixes

f/groupMarkers/fn_groupData.sqf, mission.sqm
Adds template units for Contact factions (NPR, LDF). Also increments the version counter in the mission title. Template units provided by @costno 
Fixes the remaining checkbox in #254
=> Mission.sqm changes for Contact

f/briefing/f_orbatNotes.sqf
* Add markers for specialists and cargo slots
* Add compatibility for singleplayer mode
* Add helper function `_fnc_getMarker` to cut down on duplicate code
Vehicles:
Vehicles:
If a vehicle only has units from a single group, do we want to only show the marker for the vehicle and not for the individual slots?
=> Orbat: Marker for specialists and cargo

README.md, description.ext
(version number in mission.sqm has already been updated to 3.5.4 in #263)
=> Change F3 version to 3-5-4

f/assignGear/f_assignGear_ctrg.sqf
Fixes #271 by reversing CTRG launcher types.
=> Fix issue 271

f/briefing/f_orbatNotes.sqf
=> Issue 265: ORBAT: Remove single letter indicating the side/faction for group names

description.ext, f/missionConditions/f_conditionNotes.sqf, f/missionConditions/f_setMissionConditions.sqf, f/missionConditions/fn_SetFog.sqf, f/missionConditions/fn_SetTime.sqf, f/missionConditions/fn_SetWeather.sqf, f/missionConditions/fn_SetWind.sqf
=> Mission condition notes rebase

f/assignGear/f_assignGear_attachments.sqf
command is now on main as of 2.02
=> 312 removeAllSecondaryWeaponItems

f/assignGear/f_assignGear_AI.sqf
Issue #316
Expands the list of recognised classes in assignGear AI
=> 316 assignGear AI expansion

ws_fnc/AI/fn_createGarrison.sqf
#321 
Made createGarrison better in the following ways:
- default handling for Contact factions (LDF, Spetsnaz)
- better default class distribution
- added optional parameter to run assignGear AI on spawned units
- added thing to add spawned units to Zeus (#277 )
=> createGarrison improvements

f/groupMarkers/f_setLocalGroupMarkers.sqf
=> Issue #333: Remove "Unit" requirement in variable name for specialist markers

f/assignGear/f_assignGear_3IFB.sqf, f/assignGear/f_assignGear_aaf.sqf, f/assignGear/f_assignGear_clothes.sqf, f/assignGear/f_assignGear_csat.sqf, f/assignGear/f_assignGear_csatPacific.sqf, f/assignGear/f_assignGear_ctrg.sqf, f/assignGear/f_assignGear_fia.sqf, f/assignGear/f_assignGear_gendarmerie.sqf, f/assignGear/f_assignGear_ldf.sqf, f/assignGear/f_assignGear_nato.sqf, f/assignGear/f_assignGear_natoPacific.sqf, f/assignGear/f_assignGear_natoWoodland.sqf, f/assignGear/f_assignGear_npr.sqf, f/assignGear/f_assignGear_spetsnaz.sqf, f/assignGear/f_assignGear_syndikat.sqf, f/briefing/f_orbatNotes.sqf, mission.sqm, ws_fnc/AI/fn_createGarrison.sqf
Initial PR for early 3.5.5 bugfixes
=> 3.5.5 bugfixes 1

README.md, description.ext, mission.sqm
No, I don't know why dev branch never received the 3.5.4 number.
=> Update version number

f/casualtiesCap/f_CasualtiesCapCheck.sqf
Reverts folkarps/F3#335
This change will be moved to a later release in order to expedite 3.5.5
=> Revert "Issue #329: Make CasCap work with reinforcements"

f/zeus/fn_zeusAddAddons.sqf, f/zeus/fn_zeusInit.sqf
=> Implement Lexer's Zeus fix option

f/assignGear/f_assignGear_gendarmerie.sqf
Undefined clothing classes were causing problems as per #337. They are now defined as empty arrays.
=> 337 Gendarmerie clothes classes

f/assignGear/f_assignGear_aaf.sqf, f/assignGear/f_assignGear_fia.sqf
Per #346 switch the AAF and FIA ARs from Mk200 to LIM-85.
=> 346 Change AAF and FIA ARs

README.md, description.ext, mission.sqm
Version numbering and things for 3.5.6
=> 3.5.6 release changes

f/casualtiesCap/f_CasualtiesCapCheck.sqf
=> Issue329 capcap reinforcements

f/casualtiesCap/f_CasualtiesCapCheck.sqf
...And to remove leader stability issue
The more I read CasCap, the more I hated how I'd done the JIP update. The logic is heavily group-centric, but this only makes sense in the "group" mode and confuses things in the, more common, "side mode". So, this is a rewrite that makes the logic much less group-centric in the "side" mode to aid readability and maintainability.
I highly suspect the issue we had in format testing were due to a weird interaction between `leader` and `playableUnits` in the case of a dead unit. Thus this also removes the `leader` stipulation from `_onlyPlayable` and `_factions`, which was IMO counter-intuitive to begin with.
=> [329] Rewrite CasCap logic to be less group-centric for readability
