f/common/functions.hpp, f/disableThermals/fn_disableThermals.sqf, init.sqf
F3 Disable Thermals component - Disables thermals on all vehicles present at the start of a mission. Has a mechanism to exempt certain vehicles or vehicle class (similar to authorised crew check).
Enabled by default.
Vehicles with thermals enabled are generally discouraged in FA missions, especially those used by players. This component inverts the responsibility of missionmakers to this end: now they must actively enable thermals where they want them, instead of actively having to remember to disable them.
=> Added Added F3 Disable Thermals component

f/nametag/include/f_nametagBrief.sqf
Accidentally made it so NO BRIEFING would show if CBA was present. This fix makes it so that a shortened briefing will show, as intended.
=> Quick hotfix

f/nametag/functions/fn_nametagCache.sqf
Pulling a change I made earlier today on WH nametags main branch -- if you're in third person and in a vehicle, no other units within your vehicle will be shown. This avoids a LOT of clutter, especially in large transports.
=> QoL Change - Tag Clutter

f/assignGear/f_assignGear_fiaAK_light.sqf, f/assignGear/f_assignGear_fiaAK_standard.sqf
Ref: #10 
Redefine `_carbine` as an array before the vehicle `#include` bit, to avoid breaking `selectRandom` in `f_assignGear_fia_v.sqf`.
```
_carbine = [_carbine];
```
It's perhaps a bit "hacky" instead of shifting the select random to the base gear file `f_assignGear_fiaAK.sqf`, but it does the job.
=> Issue-10: Temporary fix to prevent issues with FIA AK vehicle loadout

f/preMount/fn_mountGroups.sqf, mission.sqm
Added preMount game logics back to mission.sqm as it is seemingly no longer broken.
Changed preMount to use synchronized objects instead of group/vehicle names which was prone to error.
See also issue #45.
=> Issue 45: Bring back F3 pre-mount component

ws_fnc/AI/fn_enterBuilding.sqf
The problem was that `_bposleft` was set to `_bposarray` without copying the array.
Later on in the code `bposleft` was modified and then in line 116 `_bposarray` was used and it was expected not to have changed.
=> ws_fnc resolved division by zero issue

ws_fnc/AI/fn_createGarrison.sqf
Changes:
- Add support for factions. (issue #42)
- Using `params` (issue #24)
- Add parameter to ignore already garrisoned buildings (useful for overlapping garrisons)
=> Issue 42: Add support for factions to ws_fnc_createGarrison

mission.sqm
This PR resolves issue #122.
I tested it, and the default loadout didn't change for any of the new helicopter types. So it was a simple search and replace of the vehicle types in question.
=> Issue 122: Replace helicopters with dynamic loadout variants

mission.sqm
**Warning: do not merge this PR unless PR #124 is already merged.
Once #124 is merged, there should only be one single commit in this pull request.
In case #124 is not going to be merged, I will update this pull request accordingly.**
Remove disableTIEquipment in mission.sqm due to collision with _disable thermals component_.
This was probably just an oversight when the _disable thermals component_ was initially merged/enabled.
The reasoning behind this change is: When a vehicle is excluded from the _disable thermals component_, the missionmaker would also have to remove this line from the init field of the vehicle. Because otherwise its thermals would still be disabled, even when they shouldn't.
=> Issue 129: Remove disableTIEquipment in mission.sqm

f/preMount/fn_mountGroups.sqf, mission.sqm
Revert to string arrays instead of group names, because if a synced unit was not slotted, then the whole group would not have been mounted.
Related to issue #45 and pull request #97.
=> preMount: Switch back to group names as strings.

f/FTMemberMarkers/fn_SetLocalFTMemberMarkers.sqf, f/nametag/f_nametagInit.sqf
See issue #152.
I didn't want to add this check for every component that's not useful to logic units, because it'd require a check for the player's side which requires waiting for the playing to not be Null.
But this might break components or inadvertently change the initialization order of the components which might lead to other unforeseen consequences.
So I think it's better to only disable components which are actively causing problems for logic units.
=> Issue 152: don't run nametag and FTMemberMarkers for virtual entities

briefing.sqf
Don't show zeus briefing for virtual spectators.
And deduplicate debug messages in `briefing.sqf`.
See issue #151.
=> Issue 151: Don't show zeus briefing for virtual spectators.

f/setAISkill/f_setAISkill.sqf
We cannot use `params` here because the argument is an array of objects.
With the `params` change, we changed the behaviour because we expected an array that contains the array of units instead. This reverts it back to the old documented behaviour.
No additional typechecks are needed as `f_fnc_setAISkill` is called and `getVariable` is used on each array element. Both would throw a script error if the element wasn't an object.
=> setAISkill: Revert behaviour of arguments.

f/setTeamColours/f_setTeamColours.sqf
since Arma 3 1.62 `assignTeam` has global effect, which leads to the "problem" that teamcolors are reset when someone reconnects.
With this PR, the component runs only one one machine (the group leader's) to avoid this issue.
(Note: It will still reset the colors if the team leader reconnects, but I think this is okay.)
Related to issue #142.
=> issue 142: setTeamColours: fix JIP/locality issue

f/FTMemberMarkers/f_localFTMemberMarker.sqf, f/authorisedCrew/fn_authorisedCrewCheck.sqf, f/briefing/f_loadoutNotes.sqf, f/dynamicViewDistance/fn_ehSetViewDistance.sqf, f/groupMarkers/f_setLocalGroupMarkers.sqf, f/groupMarkers/fn_localGroupMarker.sqf, f/groupMarkers/fn_localSpecialistMarker.sqf, f/mapClickTeleport/fn_mapClickTeleportParachute.sqf, f/missionConditions/fn_SetFog.sqf, f/missionConditions/fn_SetTime.sqf, f/setGroupID/fn_setGroupID.sqf
Add typechecks to `params`.
Replace `BIS_fnc_vectorAdd` with `vectorAdd`.
Note: This pull request does not completely resolve issue #139.
=> Issue 139: Add more type-checks for 'params'

f/assignGear/f_assignGear_AI.sqf
Use `"r"` class for other soldier types, that have not been defined in `_unitClasses` at an earlier point.
This is less dangerous than setting the `_defaultclass` to `"r"` which many missionmakers do.
Setting the `_defaultclass` has the side-effect, that it potentially also affects many other non-soldiers (e.g. ~~civilians or other~~ non-combatant units like Survivor, Rifleman (unarmed), Deck Crew, (Range Master, Fighter Pilot, Competitor), ...) that should not be armed.
This PR protects missionmakers from that mistake.
=> AssignGearAI: Use "r" class for other soldiers

f/groupMarkers/fn_localGroupMarker.sqf
Previously, markers for all possible groups were created at position `[0,0]` and they did not seem to update for JIP groups. This pull request aims to solve both of these issues.
When testing this I suggest using multiple people, the dedicated server, and specialist slots (to test both group- and specialist-markers simultaneously).
=> groupMarkers: support JIP groups

f/mapClickTeleport/fn_mapClickTeleportBriefing.sqf
Fixes issue #208.
Previously the function was called with parameters only sometimes but it only worked with parameters.
Now (since #209) we no longer need the parameter.
=> Issue 208: mapClickTeleportBriefing no longer requires a parameter

f/assignGear/f_assignGear_3IFB.sqf, f/assignGear/f_assignGear_3IFB_light.sqf, f/assignGear/f_assignGear_3IFB_standard.sqf, f/assignGear/f_assignGear_3IFB_v.sqf, f/assignGear/fn_assignGear.sqf
See #212.
I took the syndikat files from #215 as a base and adjusted the Sniper/Spotter magazine counts to balance them wrt to the other factions and their magazines.
`f_assignGear_3IFB.sqf` is from costno.
Open issues for this or a future PR:
* ~~Remove FIA AK~~ New issue created for this #228
=> adding 3IFB to assignGear

f/assignGear/f_assignInsignia.sqf, f/briefing/fn_createBriefing.sqf, f/groupMarkers/f_setLocalGroupMarkers.sqf, f/groupMarkers/fn_groupData.sqf
assignGear accepts some faction aliases for use with Virtual Faction such as "aaf" for "ind_f". This PR adds those aliases to other components to better accommodate new VF-only factions, specifically NPR.
Also updates groupMarkers to reflect than NPR will be OPFOR in the template.
Components affected: groupData, assignInsignia, briefing
=> Add virtual faction aliases to other components

f/missionConditions/fn_SetWeather.sqf
#280
After some playing around I ended up dialing down the fog a lot for all rain weather settings. The main problem is that fog tends to wash out dark colors without affecting the actual light levels, which makes stormy scenes look much brighter than it should (the fact that Arma doesn't really do dark clouds very well to begin with doesn't help).
All weather settings were tested at sea level and at the highest point on Malden, which is the highest point I could find in BI maps.
The old stormy:
The new stormy:
An in-between. Note the lower contrast between the dark and light parts of the cloud; I don't think it really comes through in this screenshot but in game it makes the scene look a lot brighter overall, too bright for a storm.
=> i280 - f_fnc_setWeather rain fog

f/assignGear/f_assignGear_ldf.sqf, f/assignGear/f_assignGear_syndikat.sqf, f/groupMarkers/fn_groupData.sqf
Fixes issue #292 by changing LDF AR mags to red.
Fixes issue #293 by changing NPR "IFV" group data to "TECH" in parity with FIA, etc.
Fixes issue #282 by changing the NATO Mediterranean ghillie to its equivalent NATO Pacific ghillie.
=> Fixes for 293 282 and 292

description.ext, f/setAISkill/f_setAISkill.sqf
This PR addresses #296 by changing the default AI skill parameter to Medium (from High). It also adjusts the base skill values to reduce AI accuracy, which should make the parameter values better calibrated for LAMBS Danger rather than forcing us to only ever use Low.
=> 296 AI skill changes

mission.sqm
Changes CSAT template Marid groups to make the gunner the group leader, instead of the driver, in accordance with #278.
=> 278 Marid group leadership

f/assignGear/f_assignGear_csat.sqf, f/assignGear/f_assignGear_csatPacific.sqf
In accordance with #301, this PR changes CSAT LBV harnesses to tac vests. It also provides the LBV classnames in a comment with instructions to use them if using assignGear AI for CSAT enemies.
=> 301 CSAT tac vests

f/assignGear/f_assignGear_3IFB.sqf, f/assignGear/f_assignGear_3IFB_standard.sqf, f/assignGear/f_assignGear_aaf.sqf, f/assignGear/f_assignGear_aaf_standard.sqf, f/assignGear/f_assignGear_csat.sqf, f/assignGear/f_assignGear_csatPacific.sqf, f/assignGear/f_assignGear_csatPacific_standard.sqf, f/assignGear/f_assignGear_csat_standard.sqf, f/assignGear/f_assignGear_ctrg.sqf, f/assignGear/f_assignGear_ctrg_standard.sqf, f/assignGear/f_assignGear_fia.sqf, f/assignGear/f_assignGear_fia_standard.sqf, f/assignGear/f_assignGear_ldf.sqf, f/assignGear/f_assignGear_ldf_standard.sqf, f/assignGear/f_assignGear_nato.sqf, f/assignGear/f_assignGear_natoPacific.sqf, f/assignGear/f_assignGear_natoPacific_standard.sqf, f/assignGear/f_assignGear_natoWoodland.sqf, f/assignGear/f_assignGear_natoWoodland_standard.sqf, f/assignGear/f_assignGear_nato_standard.sqf, f/assignGear/f_assignGear_npr.sqf, f/assignGear/f_assignGear_npr_standard.sqf, f/assignGear/f_assignGear_spetsnaz.sqf, f/assignGear/f_assignGear_spetsnaz_standard.sqf, f/assignGear/f_assignGear_syndikat.sqf, f/assignGear/f_assignGear_syndikat_standard.sqf, mission.sqm
Per #290, this adds new Light Vehicle crew classes to assignGear.
"lvc" Light Vehicle Crew - identical to "vc" except it gets a carbine
"lvd" Light Vehicle Driver - identical to "vd" except it gets a carbine and binocs
Notes:
- new classes receive the standard uniforms, helmets, and rigs as they are not included in any of the special outfit arrays
- not added to light loadouts due to pending removal of light loadouts
- already has binocs as a variable due to pending change
- added Crew instead of Commander/Gunner as few light vehicles require a third crew-member and there would be no difference in gear anyway
- drivers get binocs because they usually have the best opportunity to use them in a light vehicle crew
=> 290 light vehicle crews

f/assignGear/fn_assignGear.sqf, f/briefing/fn_createBriefing.sqf
#331 
Tested locally. AssignGear and createBriefing appear to work correctly, and the game doesn't crash if you delete all the affected files. createBriefing looks a bit complex because it needs to bypass the exitWith or it won't detect that a briefing hasn't been loaded.
=> #331 added __has_include protection to createBriefing and assignGear

f/casualtiesCap/f_CasualtiesCapCheck.sqf
See #329.
Previously, the problem was that the `_onlyPlayers` was set to true by default and then at the beginning, it only used groups that had a playable leader. I have moved this check into the loop now, such that previously empty groups are also counted if they have players.
Also, i set the `_started` variable in the same loop to avoid duplicating the unit-counting logic.
=> Issue #329: Make CasCap work with reinforcements
